### PR TITLE
As a tachiyomi layout user, bring the detection of a file named cover.jpg in the series folder

### PR DESCRIPTION
**Pull request by chocoboSan**
Inspired from previously existing code, I added back the possibility to return the file named cover.jpg (https://tachiyomi.org/help/guides/reading-local-manga/) as users possessing a library well organised for tachiyomi "local source" will see their covers filles being used.

If there is a more optimal way to do so, I'd be glad to update the code as it is the version I am currently running 👍

### CODE REVIEW

**Comment by chocoboSan** [comment]
Just saw the conflict! Will try to update.

**Comment by gotson** [comment]
I fail to understand what this is doing or trying to achieve.

**Comment by chocoboSan** [comment]
As I noticed, recent versions include such a detection mechanism. Guess I was just unlucky to pick version 0.53 that did not have it! Closing the PR.

**Comment by chocoboSan** [comment]
> I fail to understand what this is doing or trying to achieve.

Much simpler version of the current LocalArtworkProvider basically.

**Pull request closed without merging**
