### PR TITLE
feat(webui): Duplicate pagination links at bottom of content lists.

### LINKED ISSUE #305: [Feature Request] add navigation at the bottom of paged browsing screens
### Is your feature request related to a problem? Please describe.
I'm frustrated when I'm on a paged browsing screen and have to scroll back to the top of the page to get back to the page navigation.

### Describe the solution you'd like
It'd be nice to have the navigation buttons duplicated on the library navigation page so I don't need to scroll back up to the top of the page to get to the next one.

### Describe alternatives you've considered or other apps that can do what you want
Infinite scrolling would be nicer and that there's already an open issue for it, but this seems not-as-difficult of a request.

### Additional context
None.

### PR DESCRIPTION
**Pull request by Kussie**
This PR add a duplicate of pagination links at the bottom of the content lists where applicable and will also close #305

### CODE REVIEW

**Comment by gotson** [comment]
Ideally I'd like to hide the pagination at the bottom when there's enough screen height to show all the cards and both would show at the same time. Not sure yet how to do that though.

**Comment by Kussie** [comment]
Yeah that start's to get a bit tricky, but i believe it is doable.  Though personally i would still like to have at the bottom as well, just because it's handy to have right there if i am reading down the list.

**Comment by gotson** [comment]
I need to give it a go on various screen sizes and configurations of pages.

**Comment by Kussie** [comment]
Should be good hopefully.  Looks good for me on my screen and the various mobile device sizes i tried.  So hopefully that repeats itself for you :)

**Pull request merged**
