### PR TITLE
feat(webui): allow page navigation with mouse wheel

### PR DESCRIPTION
**Pull request by davidkna**
This PR allow using the mouse wheel to navigate to the next/previous pages in the `PagedReader`

### CODE REVIEW

**Comment by gotson** [comment]
Thanks for your PR, I'm still trying to find a mouse so I can test it!

**Comment by davidkna** [comment]
I've updated the PR a bit to better handle pixel-based scrolling devices.
If you use a laptop, you should be able to trigger the wheel events without an external mouse with regular mousepad scrolling gestures.

**Comment by gotson** [comment]
I gave it a try but i experience weird behaviour:
- with the trackpad, because of the inertia of the scroll, it will change multiple pages when scrolling. It is really a problem when reading in `Fit to width` and you need to scroll down to the page, because whenever you hit the bottom, instead of the scroll 'bouncing', it will change page.
- with a mouse, it kinda works on `Fit to width` when you reach the bottom of the page. However, when in `Fit to screen` or `Fit to height`, I need to roll the wheel multiple times to get the page to turn.

**Comment by davidkna** [comment]
> with the trackpad, because of the inertia of the scroll, it will change multiple pages when scrolling. It is really a problem when reading in `Fit to width` and you need to scroll down to the page, because whenever you hit the bottom, instead of the scroll 'bouncing', it will change page.

I will change this to require that movement needs to come to a stop for some time when reaching the bottom the page before wheel movement can trigger a page switch.

> with a mouse, it kinda works on `Fit to width` when you reach the bottom of the page. However, when in `Fit to screen` or `Fit to height`, I need to roll the wheel multiple times to get the page to turn.

How many pixels does your mouse move on a single rotation? I can change the `PAGE_SWITCH_THRESHOLD ` to reflect this. My regular mouse unfortunately only cause line wheel events.

**Comment by davidkna** [comment]
Updated!

**Comment by davidkna** [comment]
Any updates on this?

**Comment by gotson** [comment]
I just tried it again:
- with a trackpad it's not as buggy as it was, still the experience is not great
- with a mouse it doesn't really work, I need to roll the wheel like 3-4 times for the page to change

**Comment by davidkna** [comment]
> I just tried it again:
> 
> * with a trackpad it's not as buggy as it was, still the experience is not great

I don't think there's much I can do about this.

> * with a mouse it doesn't really work, I need to roll the wheel like 3-4 times for the page to change

If further decreased the `PAGE_SWITCH_THRESHOLD` to 13px which is about three times lower. But 16px might be a better a value because it's the default browser font size.

**Pull request closed without merging**
