### PR TITLE
Feature: Full screen shortcut support

### PR DESCRIPTION
**Pull request by tahngarth**
Tested with iPad ios 13 safari, Samsung Browser and Chrome on Android.
This supports full screen shortcuts when "add to desktop" or the equivalent is selected from within the web browser while on the komga page. This will trigger the web browser's full screen stand alone web app mode. It is not a full PWA implementation, so offline caching does not occur.

### CODE REVIEW

**Comment by gotson** [comment]
Testing would be required to confirm whether webui updates are seen properly on client side.

**Comment by tahngarth** [comment]
Another thing that needs to be tested is whether the display mode as "fullscreen" is appropriate. There should never be a spot where the browser's back button is needed, some sort of control is needed on the web page to be able to go back or escape the operation that's in progress. I looked around and couldn't find any examples of the interface that conflicted with this. 

If "fullscreen" is not valid, "standalone" can be used instead.

**Comment by gotson** [comment]
Back button navigation is required for some navigation paths, and there is no duplication of visual ui element to mimick the back button.

Good point though as full-screen navigation, as well as iOS, do not have back buttons.

**Comment by tahngarth** [comment]
So whenever I use komga lately I make a point to not use the back button on my phone. You can't always go back one page, but there's never been a time where I was completely borked, I could at least use the hamburger menu. Some slight tweaks might be nice, but in general I can't find a place where fullscreen is completely inappropriate.

**Pull request closed without merging**
