### PR TITLE
URLDecoder

### PR DESCRIPTION
**Pull request by wushuo894**
Fixed an issue where image files in epub could not be displayed normally when the file name was Chinese

### CODE REVIEW

**Comment by wushuo894** [comment]
> Fixed an issue where image files in epub could not be displayed normally when the file name was Chinese

**Comment by wushuo894** [comment]
Xnip2024-03-11_13-28-27

**Comment by wushuo894** [comment]
Xnip2024-03-11_13-33-27

**Comment by wushuo894** [comment]
> Xnip2024-03-11_13-28-27

Some of the Mimetypes fetched by epub contain \r\n

**Comment by wushuo894** [comment]
> Xnip2024-03-11_13-33-27

Chinese and url encoding conversion problems

> Xnip2024-03-11_13-33-27

Chinese and url encoding conversion problems

**Comment by gotson** [comment]
can you please create an issue first, and provide the file that causes the issue?

**Comment by wushuo894** [comment]
> can you please create an issue first, and provide the file that causes the issue?

ok

**Comment by gotson** [comment]
> Xnip2024-03-11_13-28-27

this seems to indicate that the file is incorrect, according to https://www.w3.org/TR/epub/#sec-zip-container-mime
> The mimetype file MUST NOT contain any leading or trailing padding or white space.

**Comment by wushuo894** [comment]
> > Xnip2024-03-11_13-28-27
> 
> this seems to indicate that the file is incorrect, according to https://www.w3.org/TR/epub/#sec-zip-container-mime
> 
> > The mimetype file MUST NOT contain any leading or trailing padding or white space.

This is true, but the epub can be opened in apple reader
Xnip2024-03-11_14-41-25

**Comment by wushuo894** [comment]
> > > Xnip2024-03-11_13-28-27
> > 
> > 
> > this seems to indicate that the file is incorrect, according to https://www.w3.org/TR/epub/#sec-zip-container-mime
> > > The mimetype file MUST NOT contain any leading or trailing padding or white space.
> 
> This is true, but the epub can be opened in apple reader Xnip2024-03-11_14-41-25

Xnip2024-03-11_14-43-32

**Comment by gotson** [comment]
> > > Xnip2024-03-11_13-28-27
> > 
> > 
> > this seems to indicate that the file is incorrect, according to [w3.org/TR/epub/#sec-zip-container-mime](https://www.w3.org/TR/epub/#sec-zip-container-mime)
> > > The mimetype file MUST NOT contain any leading or trailing padding or white space.
> 
> This is true, but the epub can be opened in apple reader Xnip2024-03-11_14-41-25

the file you provided in #1442 is correctly detected as EPUB in Komga

**Comment by wushuo894** [comment]
> > > > Xnip2024-03-11_13-28-27
> > > 
> > > 
> > > this seems to indicate that the file is incorrect, according to [w3.org/TR/epub/#sec-zip-container-mime](https://www.w3.org/TR/epub/#sec-zip-container-mime)
> > > > The mimetype file MUST NOT contain any leading or trailing padding or white space.
> > 
> > 
> > This is true, but the epub can be opened in apple reader Xnip2024-03-11_14-41-25
> 
> the file you provided in #1442 is correctly detected as EPUB in Komga

[人间系列01 零崎双識的人間試験.epub.zip](https://github.com/gotson/komga/files/14566783/01.epub.zip)

This is the file that failed to identify

**Comment by gotson** [comment]
> > > > > Xnip2024-03-11_13-28-27
> > > > 
> > > > 
> > > > this seems to indicate that the file is incorrect, according to [w3.org/TR/epub/#sec-zip-container-mime](https://www.w3.org/TR/epub/#sec-zip-container-mime)
> > > > > The mimetype file MUST NOT contain any leading or trailing padding or white space.
> > > 
> > > 
> > > This is true, but the epub can be opened in apple reader Xnip2024-03-11_14-41-25
> > 
> > 
> > the file you provided in #1442 is correctly detected as EPUB in Komga
> 
> [人间系列01 零崎双識的人間試験.epub.zip](https://github.com/gotson/komga/files/14566783/01.epub.zip)
> 
> This is the file that failed to identify

thanks, you should probably have started by providing the file

**Pull request closed without merging**
