### PR TITLE
feature(webui): add shortcut information menu.

### PR DESCRIPTION
**Pull request by primetoxinz**

### CODE REVIEW

**Comment by gotson** [comment]
If you install the commit hooks (`npm i` in the root folder), then it should lint for prod before committing.

**Comment by gotson** [comment]
Good news, it works nicely in the dark theme :)

However on mobile the display is tight. Should we disable the button altogether on `xs` screens, which usually don't have a keyboard anyway ?

And i was thinking, maybe we should pull the whole dialog as a component, the `BookReader` component starts to be really big, every small bit will help.

Screenshot 2020-07-24 at 10 29 27
Screenshot 2020-07-24 at 10 29 46

**Comment by primetoxinz** [comment]
I will make it look better in mobile and I'll also extract it as a component. Also I might do a later pass on the reader to lower the bulk of it, cause I do agree it's getting pretty heavy.

**Comment by primetoxinz** [comment]
2020-07-24-184721_375x747_scrot
New look on mobile

**Pull request merged**
