### PR TITLE
Push container to GHCR & set source label on container

### PR DESCRIPTION
**Pull request by cdloh**
Some people prefer to pull containers from GHCR so I've setup the CI/CD to do that.

Whilst at it I added the source label to the containers so that tools like Renovate can find the source for release notes.

If you'd prefer this work as two seperate MRs & commits I'm happy to split them up.

### CODE REVIEW

**Comment by gotson** [comment]
> Whilst at it I added the source label to the containers so that tools like Renovate can find the source for release notes.

I'm not familiar with Renovate nor that label, could you share some documentation on how that works?

> Some people prefer to pull containers from GHCR so I've setup the CI/CD to do that.

Not very familiar with GHCR either, i thought it was mirroring Dockerhub. Would you have some context/background on GHCR?

**Comment by cdloh** [comment]
> I'm not familiar with Renovate nor that label, could you share some documentation on how that works?

The label itself is just part of the [open container spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys). All it does is add metadata to the container image that people can read.

Renovate [is a dependency update tool](https://github.com/renovatebot/renovate) (think dependabot). 

If you add the annotation when Renovate creates MRs it can find change logs for releases. Documentation [here](https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md). Sample MR [here](https://github.com/onedr0p/home-ops/pull/3825).

> Some people prefer to pull containers from GHCR so I've setup the CI/CD to do that.

[Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) is just another container registry much the same as docker hub. It doesn't mirror dockerhub as such but provides the same functionality. Publishing it there provides another registry for people to pull the image from.

If you would rather these split up as two seperate MRs / feat happy to do so :)

**Comment by gotson** [comment]
I read:

> org.opencontainers.image.source URL to get source code for building the image (string)

Should it be the source _repo_, or the source _Dockerfile_?

Wondering how Renovate would be used, given Komga is not a dependency, but an app itself.

---

About GHCR, i'm wondering, where does it stop ? If we add one, then we will be asked to add another one, then another one.

**Comment by cdloh** [comment]
> Should it be the source repo, or the source Dockerfile?

Source repo.

> Wondering how Renovate would be used, given Komga is not a dependency, but an app itself.

Komga is a dependency in Gitops repos for things like Docker Compose & Kubernetes repos.

See [this example MR](https://github.com/onedr0p/home-ops/pull/3808) where a Renovate bot is upgrading a container image. See the Release Notes section with the subheading you can expand which will show release notes.

If the label is not set renovate cannot find those release notes.

It's considered best practise to label your images with relevant information See [Redhat post about it](https://developers.redhat.com/articles/2021/11/11/best-practices-building-images-pass-red-hat-container-certification#best_practice__7__embed_license_information_inside_your_image).

I thought it'd just be easiest to start with this tag.

---

> About GHCR, i'm wondering, where does it stop ? If we add one, then we will be asked to add another one, then another one.

I can understand that. In my mind you would want it available in at least two places if the primary source goes down.

Since GHCR is (at least in my experience) widely accepted by the community it seems like a good option to have as a second location.

If you'd rather not have some of these changes or as seperate MRs please let me know.

**Comment by gotson** [comment]
Thanks for taking the time to answer my questions

**Pull request merged**
