### PR TITLE
build(docker): update docker images

### PR DESCRIPTION
**Pull request by ereneroglum**
This commit updates docker images for amd64 and
arm64 to ubuntu 24.04. This cleans up Dockerfile template and brings jpegxl support for arm64 platform.

### CODE REVIEW

**Comment by gotson** [comment]
ubuntu 24.04 still packages libjxl 0.7, which is not good. We also don't want to install JDK from apt, but use the temurin base image.

I will not be merging this PR as-is.

**Comment by ereneroglum** [comment]
> ubuntu 24.04 still packages libjxl 0.7, which is not good. We also don't want to install JDK from apt, but use the temurin base image.
> 
> I will not be merging this PR as-is.

Temurin part should be trivial.

Would you be willing to merge if it is adopted to Ubuntu 24.10 which packages libjxl 0.10.3 or Alpine 3.20 which packages libjxl 0.10.2 ?

**Comment by gotson** [comment]
I will not move the image to Alpine, neither to a non-LTS ubuntu version. Ideally i want to use the Temurin base image, but had to use Ubuntu base and temurin layer for extra packages.

Can you maybe clarify what you intend to solve with this PR exactly ?

**Comment by ereneroglum** [comment]
Of course, I want to bring jxl support for arm64 target. Alternatively libjxl may also be recompiled for Ubuntu 22.04.

**Comment by ereneroglum** [comment]
Also [Temurin base image uses Ubuntu](https://github.com/docker-library/docs/tree/master/eclipse-temurin#eclipse-temurinversion). There is no need to bring an extra layer if you do not want to.

**Comment by gotson** [comment]
> Of course, I want to bring jxl support for arm64 target. Alternatively libjxl may also be recompiled for Ubuntu 22.04.

thanks, that was not clear.



> Also [Temurin base image uses Ubuntu](https://github.com/docker-library/docs/tree/master/eclipse-temurin?rgh-link-date=2024-08-21T02%3A38%3A50Z#eclipse-temurinversion). There is no need to bring an extra layer if you do not want to.

i know, but they use a specific version. If you want to move to another ubuntu base, you cannot use the temurin image until they update. But by using their layer, you can benefit from the temurin image on another base, which is what Komga currently does.

---

libjxl need to be at least 0.8.2 because of some CVE, unfortunately Ubuntu 24.04 still packs 0.7. Ubuntu 24.10 is not yet stable, so that's not an option for now. Libjxl official releases do not have arm64 binaries.

**Pull request closed without merging**
