### PR TITLE
feat(webui): dark mode as in #179

### PR DESCRIPTION
**Pull request by Shadowfied**
I added a toggle for Vuetifys dark theme as previously mentioned in #179. I looked through all UI elements I could find in the frontend in an empty library and in a library with some items added and fixed up any oddities.

### CODE REVIEW

**Comment by divinity76** [comment]
Your version of `komga-webui/src/components/ItemBrowser.vue` uses \n for newlines, 
but the master branch of `komga-webui/src/components/ItemBrowser.vue`

don't get me wrong, using \r\n is *bad* and that it should be fixed, but there should be a dedicated PR/commit to fix it, because now it's almost impossible to review the changes you did to `komga-webui/src/components/ItemBrowser.vue` because git will say "all lines changed" (from \r\n to \n )

**Comment by Shadowfied** [comment]
I'm not sure how that happened with the line endings, but to avoid confusion, the only actual change is line 181. This along with the other "as any" changes had to be made for TS to compile for me.

**Comment by divinity76** [comment]
@Shadowfied well some IDE's doesn't like \r\n (for good reason) and automatically switch it to \n when edited+saved,
and even git can be configured to automatically convert it to \n on commit (something like `* text=auto eol=lf` ), i guess it was your IDE.

**Comment by gotson** [comment]
Thanks @divinity76 for bringing this to the light, i just [fixed it](https://github.com/gotson/komga/commit/1c28a9496b7b1184d894784ea3488bf639f7a727) and added a `.gitattributes` file that will ensure this doesn't happen again in the future.

@Shadowfied can you rebase your fork on the latest `master` and update your PR with a force push?

**Comment by Shadowfied** [comment]
Closing this. See #245 instead.

**Pull request closed without merging**
